// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: services/datastore/protocols/file.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*FileResponse_File
	//	*FileResponse_Error
	Result isFileResponse_Result `protobuf_oneof:"result"`
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_services_datastore_protocols_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_file_proto_rawDescGZIP(), []int{0}
}

func (m *FileResponse) GetResult() isFileResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *FileResponse) GetFile() *File {
	if x, ok := x.GetResult().(*FileResponse_File); ok {
		return x.File
	}
	return nil
}

func (x *FileResponse) GetError() string {
	if x, ok := x.GetResult().(*FileResponse_Error); ok {
		return x.Error
	}
	return ""
}

type isFileResponse_Result interface {
	isFileResponse_Result()
}

type FileResponse_File struct {
	File *File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type FileResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*FileResponse_File) isFileResponse_Result() {}

func (*FileResponse_Error) isFileResponse_Result() {}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path      string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Ip        string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Views     int64  `protobuf:"varint,5,opt,name=views,proto3" json:"views,omitempty"`
	CreatedAt int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_services_datastore_protocols_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_file_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *File) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *File) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *File) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []*File `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
}

func (x *ListFile) Reset() {
	*x = ListFile{}
	mi := &file_services_datastore_protocols_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFile) ProtoMessage() {}

func (x *ListFile) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFile.ProtoReflect.Descriptor instead.
func (*ListFile) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_file_proto_rawDescGZIP(), []int{2}
}

func (x *ListFile) GetFile() []*File {
	if x != nil {
		return x.File
	}
	return nil
}

type SearchFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SearchFile) Reset() {
	*x = SearchFile{}
	mi := &file_services_datastore_protocols_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFile) ProtoMessage() {}

func (x *SearchFile) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFile.ProtoReflect.Descriptor instead.
func (*SearchFile) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_file_proto_rawDescGZIP(), []int{3}
}

func (x *SearchFile) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_services_datastore_protocols_file_proto protoreflect.FileDescriptor

var file_services_datastore_protocols_file_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22,
	0x52, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2a, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x1c, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x42, 0x26, 0x5a, 0x24, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x6d, 0x6e,
	0x69, 0x65, 0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_services_datastore_protocols_file_proto_rawDescOnce sync.Once
	file_services_datastore_protocols_file_proto_rawDescData = file_services_datastore_protocols_file_proto_rawDesc
)

func file_services_datastore_protocols_file_proto_rawDescGZIP() []byte {
	file_services_datastore_protocols_file_proto_rawDescOnce.Do(func() {
		file_services_datastore_protocols_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_datastore_protocols_file_proto_rawDescData)
	})
	return file_services_datastore_protocols_file_proto_rawDescData
}

var file_services_datastore_protocols_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_datastore_protocols_file_proto_goTypes = []any{
	(*FileResponse)(nil), // 0: file.FileResponse
	(*File)(nil),         // 1: file.File
	(*ListFile)(nil),     // 2: file.ListFile
	(*SearchFile)(nil),   // 3: file.SearchFile
}
var file_services_datastore_protocols_file_proto_depIdxs = []int32{
	1, // 0: file.FileResponse.file:type_name -> file.File
	1, // 1: file.ListFile.file:type_name -> file.File
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_datastore_protocols_file_proto_init() }
func file_services_datastore_protocols_file_proto_init() {
	if File_services_datastore_protocols_file_proto != nil {
		return
	}
	file_services_datastore_protocols_file_proto_msgTypes[0].OneofWrappers = []any{
		(*FileResponse_File)(nil),
		(*FileResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_datastore_protocols_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_datastore_protocols_file_proto_goTypes,
		DependencyIndexes: file_services_datastore_protocols_file_proto_depIdxs,
		MessageInfos:      file_services_datastore_protocols_file_proto_msgTypes,
	}.Build()
	File_services_datastore_protocols_file_proto = out.File
	file_services_datastore_protocols_file_proto_rawDesc = nil
	file_services_datastore_protocols_file_proto_goTypes = nil
	file_services_datastore_protocols_file_proto_depIdxs = nil
}
