// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: services/datastore/protocols/shortener.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ShortResponse_Short
	//	*ShortResponse_Error
	Result isShortResponse_Result `protobuf_oneof:"result"`
}

func (x *ShortResponse) Reset() {
	*x = ShortResponse{}
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortResponse) ProtoMessage() {}

func (x *ShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortResponse.ProtoReflect.Descriptor instead.
func (*ShortResponse) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_shortener_proto_rawDescGZIP(), []int{0}
}

func (m *ShortResponse) GetResult() isShortResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ShortResponse) GetShort() *Short {
	if x, ok := x.GetResult().(*ShortResponse_Short); ok {
		return x.Short
	}
	return nil
}

func (x *ShortResponse) GetError() string {
	if x, ok := x.GetResult().(*ShortResponse_Error); ok {
		return x.Error
	}
	return ""
}

type isShortResponse_Result interface {
	isShortResponse_Result()
}

type ShortResponse_Short struct {
	Short *Short `protobuf:"bytes,1,opt,name=short,proto3,oneof"`
}

type ShortResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ShortResponse_Short) isShortResponse_Result() {}

func (*ShortResponse_Error) isShortResponse_Result() {}

type Short struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	URL       string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Short) Reset() {
	*x = Short{}
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Short) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Short) ProtoMessage() {}

func (x *Short) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Short.ProtoReflect.Descriptor instead.
func (*Short) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *Short) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Short) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *Short) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SearchShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SearchShort) Reset() {
	*x = SearchShort{}
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchShort) ProtoMessage() {}

func (x *SearchShort) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchShort.ProtoReflect.Descriptor instead.
func (*SearchShort) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *SearchShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorts []*Short `protobuf:"bytes,1,rep,name=shorts,proto3" json:"shorts,omitempty"`
}

func (x *ListShort) Reset() {
	*x = ListShort{}
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShort) ProtoMessage() {}

func (x *ListShort) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShort.ProtoReflect.Descriptor instead.
func (*ListShort) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ListShort) GetShorts() []*Short {
	if x != nil {
		return x.Shorts
	}
	return nil
}

var File_services_datastore_protocols_shortener_proto protoreflect.FileDescriptor

var file_services_datastore_protocols_shortener_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0d, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x48, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52,
	0x4c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x1d, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x35, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x06,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x61, 0x6d, 0x6e, 0x69, 0x65, 0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_datastore_protocols_shortener_proto_rawDescOnce sync.Once
	file_services_datastore_protocols_shortener_proto_rawDescData = file_services_datastore_protocols_shortener_proto_rawDesc
)

func file_services_datastore_protocols_shortener_proto_rawDescGZIP() []byte {
	file_services_datastore_protocols_shortener_proto_rawDescOnce.Do(func() {
		file_services_datastore_protocols_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_datastore_protocols_shortener_proto_rawDescData)
	})
	return file_services_datastore_protocols_shortener_proto_rawDescData
}

var file_services_datastore_protocols_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_datastore_protocols_shortener_proto_goTypes = []any{
	(*ShortResponse)(nil), // 0: shortener.ShortResponse
	(*Short)(nil),         // 1: shortener.Short
	(*SearchShort)(nil),   // 2: shortener.SearchShort
	(*ListShort)(nil),     // 3: shortener.ListShort
}
var file_services_datastore_protocols_shortener_proto_depIdxs = []int32{
	1, // 0: shortener.ShortResponse.short:type_name -> shortener.Short
	1, // 1: shortener.ListShort.shorts:type_name -> shortener.Short
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_datastore_protocols_shortener_proto_init() }
func file_services_datastore_protocols_shortener_proto_init() {
	if File_services_datastore_protocols_shortener_proto != nil {
		return
	}
	file_services_datastore_protocols_shortener_proto_msgTypes[0].OneofWrappers = []any{
		(*ShortResponse_Short)(nil),
		(*ShortResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_datastore_protocols_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_datastore_protocols_shortener_proto_goTypes,
		DependencyIndexes: file_services_datastore_protocols_shortener_proto_depIdxs,
		MessageInfos:      file_services_datastore_protocols_shortener_proto_msgTypes,
	}.Build()
	File_services_datastore_protocols_shortener_proto = out.File
	file_services_datastore_protocols_shortener_proto_rawDesc = nil
	file_services_datastore_protocols_shortener_proto_goTypes = nil
	file_services_datastore_protocols_shortener_proto_depIdxs = nil
}
