// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: services/datastore/protocols/traffic.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IP   string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Date int64  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Visitor) Reset() {
	*x = Visitor{}
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Visitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visitor) ProtoMessage() {}

func (x *Visitor) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visitor.ProtoReflect.Descriptor instead.
func (*Visitor) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *Visitor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Visitor) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *Visitor) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type Traffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Month    string     `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Total    int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Visitors []*Visitor `protobuf:"bytes,3,rep,name=visitors,proto3" json:"visitors,omitempty"`
}

func (x *Traffic) Reset() {
	*x = Traffic{}
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traffic) ProtoMessage() {}

func (x *Traffic) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traffic.ProtoReflect.Descriptor instead.
func (*Traffic) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *Traffic) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *Traffic) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Traffic) GetVisitors() []*Visitor {
	if x != nil {
		return x.Visitors
	}
	return nil
}

type UpdateTraffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Visitor *Visitor `protobuf:"bytes,2,opt,name=visitor,proto3" json:"visitor,omitempty"`
}

func (x *UpdateTraffic) Reset() {
	*x = UpdateTraffic{}
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTraffic) ProtoMessage() {}

func (x *UpdateTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTraffic.ProtoReflect.Descriptor instead.
func (*UpdateTraffic) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTraffic) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *UpdateTraffic) GetVisitor() *Visitor {
	if x != nil {
		return x.Visitor
	}
	return nil
}

type ListTraffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traffic []*Traffic `protobuf:"bytes,1,rep,name=traffic,proto3" json:"traffic,omitempty"`
}

func (x *ListTraffic) Reset() {
	*x = ListTraffic{}
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTraffic) ProtoMessage() {}

func (x *ListTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_services_datastore_protocols_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTraffic.ProtoReflect.Descriptor instead.
func (*ListTraffic) Descriptor() ([]byte, []int) {
	return file_services_datastore_protocols_traffic_proto_rawDescGZIP(), []int{3}
}

func (x *ListTraffic) GetTraffic() []*Traffic {
	if x != nil {
		return x.Traffic
	}
	return nil
}

var File_services_datastore_protocols_traffic_proto protoreflect.FileDescriptor

var file_services_datastore_protocols_traffic_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x74,
	0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x22, 0x41, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x63, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x2c, 0x0a, 0x08, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x56, 0x69, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x08, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x51, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e,
	0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x22, 0x39, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x12,
	0x2a, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x52, 0x07, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x42, 0x26, 0x5a, 0x24, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x6d, 0x6e, 0x69, 0x65, 0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_datastore_protocols_traffic_proto_rawDescOnce sync.Once
	file_services_datastore_protocols_traffic_proto_rawDescData = file_services_datastore_protocols_traffic_proto_rawDesc
)

func file_services_datastore_protocols_traffic_proto_rawDescGZIP() []byte {
	file_services_datastore_protocols_traffic_proto_rawDescOnce.Do(func() {
		file_services_datastore_protocols_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_datastore_protocols_traffic_proto_rawDescData)
	})
	return file_services_datastore_protocols_traffic_proto_rawDescData
}

var file_services_datastore_protocols_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_datastore_protocols_traffic_proto_goTypes = []any{
	(*Visitor)(nil),       // 0: traffic.Visitor
	(*Traffic)(nil),       // 1: traffic.Traffic
	(*UpdateTraffic)(nil), // 2: traffic.UpdateTraffic
	(*ListTraffic)(nil),   // 3: traffic.ListTraffic
}
var file_services_datastore_protocols_traffic_proto_depIdxs = []int32{
	0, // 0: traffic.Traffic.visitors:type_name -> traffic.Visitor
	0, // 1: traffic.UpdateTraffic.visitor:type_name -> traffic.Visitor
	1, // 2: traffic.ListTraffic.traffic:type_name -> traffic.Traffic
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_datastore_protocols_traffic_proto_init() }
func file_services_datastore_protocols_traffic_proto_init() {
	if File_services_datastore_protocols_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_datastore_protocols_traffic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_datastore_protocols_traffic_proto_goTypes,
		DependencyIndexes: file_services_datastore_protocols_traffic_proto_depIdxs,
		MessageInfos:      file_services_datastore_protocols_traffic_proto_msgTypes,
	}.Build()
	File_services_datastore_protocols_traffic_proto = out.File
	file_services_datastore_protocols_traffic_proto_rawDesc = nil
	file_services_datastore_protocols_traffic_proto_goTypes = nil
	file_services_datastore_protocols_traffic_proto_depIdxs = nil
}
