// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.3
// source: services/multimedia/protocols/image.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSizeRequest) Reset() {
	*x = ImageSizeRequest{}
	mi := &file_services_multimedia_protocols_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSizeRequest) ProtoMessage() {}

func (x *ImageSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_multimedia_protocols_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSizeRequest.ProtoReflect.Descriptor instead.
func (*ImageSizeRequest) Descriptor() ([]byte, []int) {
	return file_services_multimedia_protocols_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageSizeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageSizeRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ImageResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResizeRequest) Reset() {
	*x = ImageResizeRequest{}
	mi := &file_services_multimedia_protocols_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResizeRequest) ProtoMessage() {}

func (x *ImageResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_multimedia_protocols_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResizeRequest.ProtoReflect.Descriptor instead.
func (*ImageResizeRequest) Descriptor() ([]byte, []int) {
	return file_services_multimedia_protocols_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageResizeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageResizeRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageResizeRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_services_multimedia_protocols_image_proto protoreflect.FileDescriptor

var file_services_multimedia_protocols_image_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x22, 0x3a, 0x0a, 0x10, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x56,
	0x0a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x27, 0x5a, 0x25, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x61, 0x6d, 0x6e, 0x69, 0x65, 0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_multimedia_protocols_image_proto_rawDescOnce sync.Once
	file_services_multimedia_protocols_image_proto_rawDescData = file_services_multimedia_protocols_image_proto_rawDesc
)

func file_services_multimedia_protocols_image_proto_rawDescGZIP() []byte {
	file_services_multimedia_protocols_image_proto_rawDescOnce.Do(func() {
		file_services_multimedia_protocols_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_multimedia_protocols_image_proto_rawDescData)
	})
	return file_services_multimedia_protocols_image_proto_rawDescData
}

var file_services_multimedia_protocols_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_multimedia_protocols_image_proto_goTypes = []any{
	(*ImageSizeRequest)(nil),   // 0: image.ImageSizeRequest
	(*ImageResizeRequest)(nil), // 1: image.ImageResizeRequest
}
var file_services_multimedia_protocols_image_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_multimedia_protocols_image_proto_init() }
func file_services_multimedia_protocols_image_proto_init() {
	if File_services_multimedia_protocols_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_multimedia_protocols_image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_multimedia_protocols_image_proto_goTypes,
		DependencyIndexes: file_services_multimedia_protocols_image_proto_depIdxs,
		MessageInfos:      file_services_multimedia_protocols_image_proto_msgTypes,
	}.Build()
	File_services_multimedia_protocols_image_proto = out.File
	file_services_multimedia_protocols_image_proto_rawDesc = nil
	file_services_multimedia_protocols_image_proto_goTypes = nil
	file_services_multimedia_protocols_image_proto_depIdxs = nil
}
