// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.3
// source: services/multimedia/protocols/video.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Frame         int32                  `protobuf:"varint,2,opt,name=frame,proto3" json:"frame,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrameRequest) Reset() {
	*x = VideoFrameRequest{}
	mi := &file_services_multimedia_protocols_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrameRequest) ProtoMessage() {}

func (x *VideoFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_multimedia_protocols_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrameRequest.ProtoReflect.Descriptor instead.
func (*VideoFrameRequest) Descriptor() ([]byte, []int) {
	return file_services_multimedia_protocols_video_proto_rawDescGZIP(), []int{0}
}

func (x *VideoFrameRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoFrameRequest) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *VideoFrameRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailRequest) Reset() {
	*x = ThumbnailRequest{}
	mi := &file_services_multimedia_protocols_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequest) ProtoMessage() {}

func (x *ThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_multimedia_protocols_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_services_multimedia_protocols_video_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbnailRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ThumbnailRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_services_multimedia_protocols_video_proto protoreflect.FileDescriptor

var file_services_multimedia_protocols_video_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x22, 0x51, 0x0a, 0x11, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x42, 0x27, 0x5a, 0x25, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x6d, 0x6e, 0x69, 0x65,
	0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_services_multimedia_protocols_video_proto_rawDescOnce sync.Once
	file_services_multimedia_protocols_video_proto_rawDescData = file_services_multimedia_protocols_video_proto_rawDesc
)

func file_services_multimedia_protocols_video_proto_rawDescGZIP() []byte {
	file_services_multimedia_protocols_video_proto_rawDescOnce.Do(func() {
		file_services_multimedia_protocols_video_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_multimedia_protocols_video_proto_rawDescData)
	})
	return file_services_multimedia_protocols_video_proto_rawDescData
}

var file_services_multimedia_protocols_video_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_multimedia_protocols_video_proto_goTypes = []any{
	(*VideoFrameRequest)(nil), // 0: video.VideoFrameRequest
	(*ThumbnailRequest)(nil),  // 1: video.ThumbnailRequest
}
var file_services_multimedia_protocols_video_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_multimedia_protocols_video_proto_init() }
func file_services_multimedia_protocols_video_proto_init() {
	if File_services_multimedia_protocols_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_multimedia_protocols_video_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_multimedia_protocols_video_proto_goTypes,
		DependencyIndexes: file_services_multimedia_protocols_video_proto_depIdxs,
		MessageInfos:      file_services_multimedia_protocols_video_proto_msgTypes,
	}.Build()
	File_services_multimedia_protocols_video_proto = out.File
	file_services_multimedia_protocols_video_proto_rawDesc = nil
	file_services_multimedia_protocols_video_proto_goTypes = nil
	file_services_multimedia_protocols_video_proto_depIdxs = nil
}
